# Generated by Django 3.0 on 2019-12-11 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('filename', models.CharField(max_length=255, verbose_name='Filename')),
                ('content', models.TextField(verbose_name='Original content when uploaded (for debug purposes)')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Saved by')),
            ],
        ),
        migrations.CreateModel(
            name='DesignTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('filename', models.CharField(max_length=255, verbose_name='Filename')),
                ('content', models.TextField(verbose_name='Template as SBML JSON')),
            ],
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sbml', models.TextField(verbose_name='Model as SBML JSON')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Modification date')),
                ('changes', models.TextField(verbose_name='Summary of changes (JSON)')),
                ('reason', models.TextField(blank=True, default='', verbose_name='Description of changes')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='wedesign.DesignModel', verbose_name='Model')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
