import * as mm from "./metabolic_model";
import * as reactions from "./page_reactions";
import * as metabolites from "./page_metabolites";
import * as compartments from "./page_compartments";
import * as stoichiometry from "./page_stoichiometry";
import * as settings from "./page_settings";
import * as simulation from "./page_simulation";
import * as history from "./page_history";
import * as dialog_reaction from "./dialog_reaction";
import * as dialog_reaction_bulkadd from "./dialog_reaction_bulkadd";
import * as dialog_reaction_delete from "./dialog_reaction_delete";
import * as dialog_metabolite from "./dialog_metabolite";
import * as dialog_save from "./dialog_save";
import * as dialog_saveas from "./dialog_saveas";
import * as dialog_compartment from "./dialog_compartment";
import { RequestHandler } from "./request_handler";
import { HistoryManager } from "./history_manager";
export declare class AppManager {
    readonly dialog_reaction: dialog_reaction.Dialog;
    readonly dialog_reaction_bulk: dialog_reaction_bulkadd.Dialog;
    readonly dialog_reaction_delete: dialog_reaction_delete.Dialog;
    readonly dialog_metabolite: dialog_metabolite.Dialog;
    readonly dialog_save: dialog_save.Dialog;
    readonly dialog_saveas: dialog_saveas.Dialog;
    readonly dialog_compartment: dialog_compartment.Dialog;
    readonly reaction_page: reactions.Page;
    readonly metabolite_page: metabolites.Page;
    readonly compartment_page: compartments.Page;
    readonly stoichiometry_page: stoichiometry.Page;
    readonly settings_page: settings.Page;
    readonly simulation_page: simulation.Page;
    readonly history_page: history.Page;
    readonly urls: any;
    readonly request_handler: RequestHandler;
    readonly glpk_worker: Worker;
    readonly viz: any;
    history_manager: HistoryManager;
    model: mm.Model;
    old_model: string;
    constructor(mm_cls: any, model_json: any, urls: any, glpk_worker: Worker, viz: any);
}
export declare function run(mm_cls: any, urls: any, glpk_worker: Worker, viz: any): void;
